### ISSUE TITLE
New join page

### ISSUE THREAD

**Issue by erskingardner** [zatzby/whynostr#38]
- [x] New design
- [x] Implement new design
- [x] Add more clients (specifically desktop)

**Comment by zatzby** [comment]
Finally getting to do some work on this page. I just pushed some code to the main branch, meant to just create a pull request but for some reason was struggling with creating pull request there. 

I imported a dropdown menu from flowbite and got it set up with links to the more "traditionally social media' based clients.

Here is a snippet: 

<script lang="ts">
    import { Button, Dropdown, DropdownItem, DropdownDivider, Chevron } from 'flowbite-svelte';
  </script>

<h1>Join</h1>
<Button><Chevron>Select your platform</Chevron></Button>
<Dropdown>
    <DropdownItem class="flex items-center justify-between"><Chevron placement="right">Android</Chevron></DropdownItem>
  <Dropdown placement="right-start">
    <DropdownItem><a rel='external' href="https://play.google.com/store/apps/details?id=com.vitorpamplona.amethyst">Amethyst</a></DropdownItem>
    <DropdownItem><a rel='external' 
....
....



Is this an ok setup? Is there a better dropdown menu plugin you like, or a different interface for selecting from items..I just found this one online searching on google. 


Overall really excited to be using svelte and learning a little bit slowly but surely. So crazy you can just import these different tools so quickly and get things up and running.

It all reminds me of this quote "Any sufficiently advanced technology is indistinguishable from magic."

**Comment by erskingardner** [comment]
Cool - since it's actually not that much info (e.g. it's an easy amount for the human eye to scan and parse quickly)I think I would just put the platforms as headings on the page and then the clients under each heading. No need for dropdowns or tabs or anything.

**Comment by zatzby** [comment]
Sounds good. I will make adjustments later today and turn platforms into headings with clients listed below. Thanks for suggestion. 🤙
